Cd ls
KatyaKos/software_design-1 pull request #1
Opened 2018-05-31 02:27 UTC by KatyaKos

2018-06-02 16:05 UTC, yurii-litvinov requested changes
- Надо ещё ревью на архитектуру оригинального решения.
- Другие команды (например, cat) не учитывают cd. Надо, чтобы они тоже знали про смену папки.
- Даже ls не учитывает cd:
```
>ls
main
test

>ls main
No such directory main
>ls CLI
.gitignore
.travis.yml
build.gradle
gradlew
gradlew.bat
out
readme.md
settings.gradle
src

>
```

2018-06-02 16:05 UTC, yurii-litvinov commented on CLI/src/main/java/ru/spbau/sd/cli/interpreter/commands/CmdCd.java
> +public class CmdCd implements Command {
Надо комментарий

2018-06-02 16:05 UTC, yurii-litvinov commented on CLI/src/main/java/ru/spbau/sd/cli/interpreter/commands/CmdCd.java
> +            outputStream.write("Error during \'cd\' command occurred. Please, provide some arguments.");
Скорее, поругаться на то, что аргументов слишком много

2018-06-02 16:05 UTC, yurii-litvinov commented on CLI/src/main/java/ru/spbau/sd/cli/interpreter/commands/CmdLs.java
> +public class CmdLs implements Command {
Тоже нужен комментарий

2018-06-02 16:05 UTC, yurii-litvinov commented on CLI/src/test/java/ru/spbau/sd/cli/interpreter/commands/CmdCdTest.java
> +        File test_dir = new File("src");
camelCase please :)

2018-06-02 16:05 UTC, yurii-litvinov commented on CLI/src/test/java/ru/spbau/sd/cli/interpreter/commands/CmdCdTest.java
> +    }
Лучше разбить на отдельные тесты

2018-06-02 16:05 UTC, yurii-litvinov commented on CLI/src/test/java/ru/spbau/sd/cli/interpreter/commands/CmdCdTest.java
> +        cdCommand.run(Collections.emptyList(),null, outputStream);
Не хватает пробела после запятой :)

2018-06-03 13:31 UTC, KatyaKos commented
Ls, Cat, Pwd видят Cd. Комментарии написала, тесты поправила. @yurii-litvinov

2018-06-03 13:45 UTC, yurii-litvinov approved these changes
👍

2018-06-03 13:46 UTC, merged